version: "3"

services:
  poll:
    restart: always
    build:
      context: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis

  redis:
    restart: always
    image: "redis:7"
    expose:
      - 6379
    networks:
      - poll-tier
      - back-tier

  worker:
    restart: always
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  db:
    restart: always
    image: "postgres:16"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - back-tier
      - result-tier

  result:
    restart: always
    build:
      context: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data:
